apiVersion: v1
kind: ConfigMap
metadata:
  name: udagram-aws
data:
  credentials: |
    [default]
    aws_access_key_id = QUtJQTMyNldITUhKTUNUQ0gyN1kK
    aws_secret_access_key = d05xbWo2b0FJVWdIeERuajhBZ1pkVVZLVG9FbnJZalU3czZZVzQxRgo=
