apiVersion: apps/v1

kind: Deployment
metadata:
  name: backend-feed
  labels:

    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: kibretzd/udagram-api-feed:v1
        ports:
          - containerPort: 8080
        envFrom: 
          - configMapRef:
              name: udagram-env
          - secretRef:
              name: my-udagram-db-secret
        volumeMounts:
          - mountPath: "/root/.aws/"
            name: my-udagram-aws
      volumes:
        - name: my-udagram-aws
          configMap:
            name: my-udagram-aws
